% A simple example on applying the ACR-BB algorithm to solve the
% single-group muticast beamforming problem

% If you have any questions or comments on using our codes, please
% feel free to contact Dr. Cheng Lu at lucheng1983@163.com.

% Reference: Cheng Lu and Ya-Feng Liu, "An Efficient Global Algorithm for 
% Single-Group Multicast Beamforming," IEEE Trans. Signal Processing. 

clear;
clc;
N = 3; % Number of antennas
M = 2; % Number of users
Max_Iter = 5; % Maximum number of iterations
epsilon = 0.0001; % The relative error tolerance

% H=randn(N,M)+i * randn(N,M); 
Hr = [[ 1.27109919,  0.62238554];
      [-0.38933997,  0.48843181];
      [-0.14073963, -0.77918651]];

Hi = [[-1.40115267, -0.17910412];
    [-0.82520195, -1.08825745];
    [-0.62317508, -0.67931762]];

H = Hr +i*Hi;
%Randomly generate complex Gaussian channel parameters

% Run our ACR-BB algorithm
[w_opt,final_lb,final_ub,lb_sequence,ub_sequence]=BranchBound_MultiCast(H',Max_Iter,epsilon);

num_iter=length(lb_sequence);
plot(1:num_iter,lb_sequence,1:num_iter,ub_sequence); % plot the lower and upper bounds sequences 

% Outputs:
% w_opt       : Returend epsilon-global optimal solution
% final_lb    : Final lower bound
% final_ub    : Final upper bound
% lb_sequence : Lower bound sequences generated by the ACR-BB algorithm
% ub_sequence : Upper bound Sequences generated by the ACR-BB algorithm